language: yaml

addons:
  firefox: "56.0"
  
services:
  - docker

before_install:
  - docker build -t abizon/lemonldapng-portail .
  - docker run -d --name portail -e LOGLEVEL=debug -p 127.0.0.1:80:80 abizon/lemonldapng-portail /bin/sh -c "/entrypoint.sh"
  - docker ps -a
  - sleep 120
  - docker exec -t -i manager /bin/bash -c "cat /etc/lemonldap-ng/lemonldap-ng.ini"
  - docker exec -t -i manager /bin/bash -c "ls /var/lib/lemonldap-ng/conf"
  - docker exec -t -i manager /bin/bash -c "cat /var/lib/lemonldap-ng/conf/lmConf.json"
  - docker logs -t --details portail

script:
  - echo OK